server:
  port: 8081

spring:
  application:
    name: edu-user-service
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
        namespace: public
        group: DEFAULT_GROUP
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      password: ""
      database: 0
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgresql"
    username: postgresql
    password: mM6hbJXelbGd
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.edu: debug

jwt:
  secret: edu-ai-platform-secret-key-must-be-at-least-256-bits-long
  expiration: 86400000